// <auto-generated />
namespace GalleryApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class newPriceValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newPriceValue));
        
        string IMigrationMetadata.Id
        {
            get { return "202001091332342_newPriceValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
